import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header/page";

import Center from "./components/center/page";
import Info from "./components/info/page";
import styles from "./page.module.scss";

const inter = Inter({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "404 Service",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={inter.className}>
        <main className={styles.main}>
          <Header></Header>
          <Center></Center>
          {children}
          <Info></Info>
        </main>
      </body>
    </html>
  );
}
