import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header/Header";

import Center from "./components/center/Center";
import Info from "./components/info/Info";
import styles from "./page.module.scss";
import { StoreProvider } from "@/store/StoreProvide";
import { Suspense } from "react";
import Loading from "./loading";

const inter = Inter({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "404 Service",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="ru">
        <body className={inter.className}>
          <main className={styles.main}>
            <Header />
            <Center />
            <Suspense fallback={<Loading />}>{children}</Suspense>
            <Info />
          </main>
        </body>
      </html>
    </StoreProvider>
  );
}
